Added test to verify if network boot uses https:// and not http://
Dasharo/open-source-firmware-validation pull request #300
Opened 2024-05-28 06:58 UTC by JanPrusinowski

Added test to verify if network boot uses https:// and not http://

2024-06-03 06:53 UTC, macpijan commented
@JanPrusinowski This commit name does not follow our guidelines. Please see other commit names in this repo.

I would expect something like: `network-boot.robot: PXE007.001 verify https not http`

2024-06-03 06:53 UTC, macpijan requested changes
@JanPrusinowski This commit name does not follow our guidelines. Please see other commit names in this repo.

I would expect something like: `network-boot.robot: PXE007.001 verify https not http`

2024-06-03 07:04 UTC, JanPrusinowski commented
@macpijan commit message fixed.

2024-06-03 07:43 UTC, macpijan approved these changes

2024-06-03 07:43 UTC, macpijan commented on dasharo-compatibility/network-boot.robot
> +    Skip If    not ${IPXE_BOOT_SUPPORT}    PXE001.001 not supported
One more @JanPrusinowski . It should be `PXE007.001` here and line below.

2024-06-04 20:10 UTC, macpijan approved these changes
Thanks for contribution, LGTM

2024-06-04 20:13 UTC, macpijan commented
Hmm one more thing @JanPrusinowski .  I can see changes in the sonoff-rest-api submodule, they should rather not belong here.
They might be caused if you have switched branches and commited using `git add -A`. It is advised to add individual files via `git add <file>` or even individual changes via `git add -p` to avoid such problems.

2024-06-17 16:22 UTC, macpijan approved these changes

2024-06-17 16:22 UTC, merged