dasharo-compatibility/cpu-fan-speed-measure.robot: Add fan control tests
Dasharo/open-source-firmware-validation pull request #505
Opened 2024-09-17 10:19 UTC by SebastianCzapla

2024-12-06 16:48 UTC, mkopec commented
What are you testing these on? We don't have ACPI driver support yet

2024-12-20 11:20 UTC, SebastianCzapla commented
> What are you testing these on? We don't have ACPI driver support yet

I commented out the tests that are based on the driver, leaving only semi-auto tests, which do not use it.

2024-12-20 12:57 UTC, SebastianCzapla commented
https://github.com/Dasharo/open-source-firmware-validation/issues/646 -> needs to be resolved to verify this PR after rebase.

2025-03-11 12:16 UTC, SebastianCzapla commented
[cpu-fan-speed-measure.zip](https://github.com/user-attachments/files/19182784/cpu-fan-speed-measure.zip)

2025-03-11 13:15 UTC, SebastianCzapla commented
[cpu-fan-speed-test-log.zip](https://github.com/user-attachments/files/19183852/cpu-fan-speed-test-log.zip)

2025-03-28 11:59 UTC, SebastianCzapla commented
[cpu-fan-speed-measure.robot_acpi_driver_branch.zip](https://github.com/user-attachments/files/19504840/cpu-fan-speed-measure.robot_acpi_driver_branch.zip)

2025-04-04 14:53 UTC, mkopec requested changes

2025-04-04 14:53 UTC, mkopec commented on platform-configs/include/default.robot
> +${FAN_RPM_MEASUREMENT_METHOD}=                      None
Unused variable. Should be FAN_SPEED_MEASURE_SUPPORT I'm guessing?

2025-04-04 14:59 UTC, SebastianCzapla commented on platform-configs/include/default.robot
> +${FAN_RPM_MEASUREMENT_METHOD}=                      None
FAN_SPEED_MEASURE_SUPPORT is already in the default.robot, this change here is artifact from intermediate stage of this PR, where I rebased onto changes made by Filip. I will remove this variable.

2025-04-04 15:03 UTC, SebastianCzapla commented on platform-configs/include/default.robot
> +${FAN_RPM_MEASUREMENT_METHOD}=                      None
https://github.com/Dasharo/open-source-firmware-validation/pull/505/commits/b6e2090ee0272672ae05a031d2b86ebf8eea3ebd

2025-04-04 15:34 UTC, mkopec approved these changes

2025-04-04 15:34 UTC, merged