Add gitcliff and reuse
Dasharo/open-source-firmware-validation pull request #529
Opened 2024-10-10 09:22 UTC by Al-an-21

2024-10-14 14:35 UTC, macpijan commented
@Al-an-21 Please take a look at your MR before submitting for review. It contains much more commmits than just your changes, and in general cannot be reviewed in a sane way. It is likely that you wanted to target `develop` branch - adjusted that.

2024-10-14 14:41 UTC, macpijan requested changes
I have a really difficult time finding git cliff changes here. If there are any, please split them into individual commits from `reuse` changes, so it can be spotted and reviewed separately from auto changes to SPDX headers.

On top of that, if there are some I would appreciate:
- some comments explaining which `ruese` commands have been used to modify the source tree
- some comments explaining whether we needed to do some changes manually, on top of the `reuse` changes

2024-10-14 14:41 UTC, macpijan commented on README.md
> +SPDX-License-Identifier: MIT
Where does the MIT came from @Al-an-21 ? We clearly already ship Apache license in this repo: https://github.com/Dasharo/open-source-firmware-validation/blob/develop/LICENSE

2024-10-31 17:56 UTC, Al-an-21 commented
I’ve organized the files and split them across two commits for clarity. Additionally, I updated the license from MIT to Apache 2.0 and expanded the README.md with detailed instructions on using reuse commands for license compliance.

2024-11-06 22:13 UTC, macpijan commented
> I’ve organized the files and split them across two commits for clarity. Additionally, I updated the license from MIT to Apache 2.0 and expanded the README.md with detailed instructions on using reuse commands for license compliance.

I fail to notice that.

reuse and cliff tools are still mixed up in the same commits, which was my main concern

![image](https://github.com/user-attachments/assets/231db36d-d0dc-44a4-8431-11a51ae6a3ba)

2024-12-01 20:27 UTC, macpijan commented
@Al-an-21 A friendly reminder that it has not been fix still :disappointed:

2024-12-16 15:51 UTC, DaniilKl commented
Continuation here https://github.com/Dasharo/open-source-firmware-validation/pull/633.

2024-12-16 15:51 UTC, closed without merging