Add vp2430 to the test environment
Dasharo/open-source-firmware-validation pull request #562
Opened 2024-11-05 08:43 UTC by JanPrusinowski

2024-11-06 20:47 UTC, macpijan commented
Let's wait for some successful test, at least basic-interfaces one.

2024-11-06 20:55 UTC, macpijan commented
@JanPrusinowski There is already older PR with this config: https://github.com/Dasharo/open-source-firmware-validation/pull/554

2024-11-12 13:55 UTC, miczyg1 requested changes

2024-11-12 13:55 UTC, miczyg1 commented on platform-configs/protectli-vp2430.robot
> +${DMIDECODE_PRODUCT_NAME}=      VP3230
3230?

2024-11-12 13:55 UTC, miczyg1 commented on platform-configs/protectli-vp2430.robot
> +${CPU}=                         Intel(R) Core(TM) i3-N305
It is `Intel(R) N100`

2024-11-12 13:55 UTC, miczyg1 commented on platform-configs/protectli-vp2430.robot
> +${CPU_MAX_FREQUENCY}=           3800
This needs to be revisited as it seems to be copy-paste

2024-11-21 11:04 UTC, macpijan commented
@philipandag  Consider looking at https://github.com/Dasharo/open-source-firmware-validation/pull/554 - maybe it has something more than present here already: https://github.com/Dasharo/open-source-firmware-validation/pull/554

2024-11-25 08:19 UTC, philipandag commented
The platform configs will be added in this PR https://github.com/Dasharo/open-source-firmware-validation/pull/554
This one is not needed anymore

2024-11-25 08:19 UTC, closed without merging