VP2430 v0.9.0-rc2 Fixes
Dasharo/open-source-firmware-validation pull request #641
Opened 2024-12-18 23:13 UTC by SebastianCzapla

2025-01-10 14:54 UTC, miczyg1 requested changes

2025-01-10 14:54 UTC, miczyg1 commented on dasharo-compatibility/usb-detect.robot
> +                ${menu}=    Read From Terminal Until    ESC to exit
What is different than in `Enter Tianocore And Return Menu` ?

2025-01-10 14:54 UTC, miczyg1 commented on dasharo-compatibility/esp-scanning.robot
> -    Skip If    not ${ESP_SCANNING_SUPPORT}    ESP002.001 not supported
Why? It may be disabled in certain builds.

2025-01-10 14:54 UTC, miczyg1 commented on dasharo-compatibility/dcu.robot
> -    Power On
Do we get rid of `Power On` now? THere are still hundreds of occurrences of Power On that should be changed to `Power Cycle On` then... Why do we change `Power On` to `Power Cycle On` only in selected places?

2025-01-10 14:54 UTC, miczyg1 commented on dasharo-security/tpm-support.robot
> +    ${result}=    Run Keyword And Ignore Error    Validate Expected TPM Via Cbmem Chip
```suggestion
    ${result}=    Run Keyword And Ignore Error    Validate Expected TPM Chip Via Cbmem
```

It is not dramatically correct. Please change the keyword name

2025-01-10 14:54 UTC, miczyg1 commented on keywords.robot
> +    Enter Submenu From Snapshot    ${boot_menu}    Ubuntu
If there is no consistency in boot options, maybe check for the option ignoring the case?

2025-01-10 15:38 UTC, SebastianCzapla commented on dasharo-compatibility/usb-detect.robot
> +                ${menu}=    Read From Terminal Until    ESC to exit
Keyword no longer exists.
![image](https://github.com/user-attachments/assets/30c089c6-c030-4e9a-8d08-84d91a76f516)

2025-01-10 15:40 UTC, SebastianCzapla commented on dasharo-compatibility/esp-scanning.robot
> -    Skip If    not ${ESP_SCANNING_SUPPORT}    ESP002.001 not supported
We check it already in the suite setup, this test was the only one that still had it, and since it's checked on suite setup we would not even reach this code.

![image](https://github.com/user-attachments/assets/3e5bda25-94c8-4ede-a179-4ff3660c6437)

2025-01-10 15:50 UTC, SebastianCzapla commented on dasharo-compatibility/dcu.robot
> -    Power On
In the early testing phase, I attributed an error I got to this keyword, but it was not right, it should be left as Power On. Will change it.

2025-01-10 15:50 UTC, SebastianCzapla commented on keywords.robot
> +    Enter Submenu From Snapshot    ${boot_menu}    Ubuntu
Good suggestion, will do.

2025-02-06 14:18 UTC, miczyg1 requested changes

2025-02-06 14:18 UTC, miczyg1 commented on dasharo-compatibility/esp-scanning.robot
> -    Skip If    not ${ESP_SCANNING_SUPPORT}    ESP002.001 not supported
Then we could move `${TESTS_IN_FIRMWARE_SUPPORT}` check to the Suite Setup too. it occurs in every test case...

2025-02-06 14:19 UTC, miczyg1 commented
Many changes I reviewd earlier simply vaporized. I must say I am a bit confused

2025-02-06 14:20 UTC, miczyg1 commented on keywords.robot
> +    Enter Submenu From Snapshot    ${boot_menu}    Ubuntu
Seems there is no change here anymore in the newest diff. What has been done to that part?

2025-02-06 14:43 UTC, SebastianCzapla commented on keywords.robot
> +    Enter Submenu From Snapshot    ${boot_menu}    Ubuntu
My attempts at case ignore were unsuccessful, in meantime, dependency on this keyword was removed in this commit: https://github.com/Dasharo/open-source-firmware-validation/pull/659/commits/e720969dc1d22c0df34b57b20842628d2c29038d

As of now, the keyword Reboot Via Ubuntu By Tianocore is not used anywhere in OSFV.

2025-02-06 14:51 UTC, SebastianCzapla commented
I should have clarified immidiately, my bad. The now gone changes were due to this branch being rebased onto https://github.com/Dasharo/open-source-firmware-validation/pull/507/

Some of the other stale changes, that I removed were things like hacky power state variables, that are no longer valid, but were during the testing.

2025-02-06 15:00 UTC, miczyg1 commented on keywords.robot
> +    Enter Submenu From Snapshot    ${boot_menu}    Ubuntu
Thanks for reference

2025-02-06 15:11 UTC, SebastianCzapla commented on dasharo-compatibility/esp-scanning.robot
> -    Skip If    not ${ESP_SCANNING_SUPPORT}    ESP002.001 not supported
Added a new commit, which isolates Suite Setup and Teardown into local keywords, which should contain proper skip conditions

2025-02-06 16:37 UTC, miczyg1 approved these changes

2025-02-06 16:38 UTC, miczyg1 commented
@SebastianCzapla can't fast-forward merge it. Needs a rebase

2025-02-06 16:41 UTC, SebastianCzapla commented
@miczyg1 rebased

2025-02-06 16:45 UTC, merged